---
language: python
services: docker

env:
  global:
    - ROLE_NAME: flameshot
  matrix:
    - MOLECULE_DISTRO: ubuntu1804

install:
  # Install test dependencies.
  - pip install molecule yamllint ansible-lint docker

before_script:
  # Use actual Ansible Galaxy role name for the project directory.
  - cd ../
  - mv ansible-role-flameshot webarchitect609.$ROLE_NAME
  - cd webarchitect609.$ROLE_NAME

script:
  # Run tests.
  - molecule test --all

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
