---

- name: "Refresh apt sources list"
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600

- name: "Ensure runtime dependencies are installed"
  ansible.builtin.apt:
    name: "{{ __flameshot_runtime_dependencies }}"
    state: "present"

- name: "Install apt package"
  ansible.builtin.apt:
    name: "{{ __flameshot_package }}"
    state: "present"
  when: not flameshot_compile

- name: "Compile"
  when: flameshot_compile
  block:

    - name: "Remove installed apt and snap {{ __flameshot_package }}"
      ansible.builtin.include_tasks: remove_apt_and_snap_installations.yml

    - name: "Check installed version"
      ansible.builtin.include_tasks: check_installed_version.yml

    - name: "Version expansion"
      ansible.builtin.include_tasks: version_expansion.yml
      when: flameshot_compile_version == "latest-stable"

    - name: "Compile version {{ flameshot_compile_version }}"
      ansible.builtin.include_tasks: compile.yml
      when: flameshot_compile_version != __flameshot_installed_version

    - name: "Clear git repo clone"
      ansible.builtin.file:
        path: "{{ __flameshot_source_dir }}"
        state: absent
      changed_when: false

- name: "Set run at startup to {{ flameshot_enable_autostart }}"
  ansible.builtin.command: flameshot config --autostart "{{ flameshot_enable_autostart }}"
  register: flameshot_config_autostart
  changed_when: "flameshot_config_autostart.rc != 0"
